name: Caddy with NaiveProxy
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y build-essential git sudo wget curl 
      
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
          
      - name: Build Caddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          ~/go/bin/xcaddy build \
            --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive \
            --with github.com/caddy-dns/cloudflare

      - name: Pack Caddy assets
        run: |
          tar czf caddy-bin.tar.gz caddy
          openssl sha256 ./caddy >sha256sum.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            sha256sum.txt
            caddy-bin.tar.gz

      - name: Set TAG_NAME with UTC date
        run: echo "DATE=v$(date -u +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
          
      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          tag_name: "Caddy(naiveproxy)-BUILD_${{ env.DATE }}"
          draft: false
          prerelease: false
          files: |
            caddy-bin.tar.gz
