name: Caddy with NaiveProxy
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build_caddy_with_naive:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    env:
      BUNDLE: caddy-forwardproxy-naive
    steps:
      - uses: actions/checkout@v5

      - run: |
          apt-get update
          apt-get upgrade
          apt-get install -y build-essential git sudo wget curl 
      
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true
          
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      
      - run: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive
      
      - name: Pack naiveproxy assets
        run: |
          mkdir ${{ env.BUNDLE }}
          cp caddy ${{ env.BUNDLE }}
          tar cJf ${{ env.BUNDLE }}.tar.xz ${{ env.BUNDLE }}
          openssl sha256 ./caddy >sha256sum.txt
          echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >>$GITHUB_ENV
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE }}.tar.xz caddy executable sha256 ${{ env.SHA256SUM }}
          path: sha256sum.txt
          
      - name: Upload caddy assets
        if: ${{ github.event_name == 'release' }}
        run: gh release upload "${GITHUB_REF##*/}"  ${{ env.BUNDLE }}.tar.xz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
