name: Caddy with NaiveProxy
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    steps:
      - uses: actions/checkout@latest

      - name: Install dependences
        run: |
          apt-get update
          apt-get upgrade -y
          apt-get install -y build-essential git sudo wget curl 
      
      - name: Setup Go
        uses: actions/setup-go@latest
        with:
          go-version: 'stable'
          check-latest: true
          
      - name: Build Caddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy=github.com/klzgrad/forwardproxy@naive

      - name: Pack naiveproxy assets
        run: |
          tar czf caddy-bin.tar.gz caddy
          openssl sha256 ./caddy >sha256sum.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@latest
        with:
          path: |
            sha256sum.txt
            caddy-bin.tar.gz
          
      - name: Release
        uses: softprops/action-gh-release@latest
        with:
          tag_name: "Caddy(naiveproxy)-BUILD_${{ env.DATE }}"
          draft: false
          prerelease: false
          files: |
            sha256sum.txt
            caddy-bin.tar.gz
